# Default values for helloworld-chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: gcr.io/sqn-development/helloworld-application
  tag: sha256:ce60d546596bde9b10b01fa5b94f4615f199a94715f8603403e178a943c6b779
  pullPolicy: Always

nameOverride: ""
fullnameOverride: ""

service:
  type: LoadBalancer
  port: 80

microservice:
  port: 3017
  version: "v0.0.1"
