apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
  namespace: {{ .Release.Name }}-namespace
data:
  SERVER_PORT: {{ .Values.microservice.port | quote }}
  APP_VERSION: {{ .Values.microservice.version | quote }}