apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "helloworld-chart.fullname" . }}
  namespace: {{ .Release.Name }}-namespace
  labels:
    app.kubernetes.io/name: {{ include "helloworld-chart.name" . }}
    helm.sh/chart: {{ include "helloworld-chart.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "helloworld-chart.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "helloworld-chart.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}@{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        env:
        - name: APP_VERSION
          valueFrom:
            configMapKeyRef:
              key: APP_VERSION
              name: {{ .Release.Name }}-configmap
        - name: SERVER_PORT
          valueFrom:
            configMapKeyRef:
              key: SERVER_PORT
              name: {{ .Release.Name }}-configmap
        